Repository httpwg/http-extensions, pull requests merged in 2021-11, with the labels that each got.

#1725 Relax requirements of NO_RFC7540 setting receiver
  draft-ietf-httpbis-priority.md
Labels: priorities, discuss

#1756 Erroring on invalid Priority Field Values in frames is optional
  draft-ietf-httpbis-priority.md
Labels: priorities, discuss

#1735 expand why and when intermediaries might want to use a frame
  draft-ietf-httpbis-priority.md
Labels: priorities, discuss

#1769 tweak NO_RFC7540 text
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1777 add parentheses around URI
  draft-ietf-httpbis-targeted-cache-control.md
Labels: editorial, targeted-cc

#1781 Add a mising "that"
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1787 Relocate appendix text to introduction
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1784 State we are using BCP 14
  draft-ietf-httpbis-priority.md
Labels: priorities

#1785 Be clearer about handling of h2 priority
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1786 explain more about the client SHOULDs wrt H2 setting
  draft-ietf-httpbis-priority.md
Labels: priorities

#1789 Remove trailing whitespace
  draft-ietf-httpbis-rfc6265bis.md
Labels: 6265bis

#1788 Less h2 bashing
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1776 Security and Privacy Considerations for Signatures
  draft-ietf-httpbis-message-signatures.md
Labels: signatures

#1795 HTTP/3 websocket should be standards track
  draft-ietf-httpbis-h3-websockets.md
Labels: h3-websockets

#1798 Fix digest in method-rsa-pss-sha512 definition
  draft-ietf-httpbis-message-signatures.md
Labels: editorial, signatures
