Repository httpwg/http-extensions, pull requests merged in 2021-12, with the labels that each got.

#1799 clarify priority parameter registration
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1797 Sec directorate review feedback
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1800 cite experiments of simpler priority schemes
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1807 Clarify the actor when reponses omit parameters
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1805 H2 priority elements might always be used
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1808 Use the full term 'priority parameters' everywhere
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1813 Tweak the server scheduling text to clarify what is covered
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1804 Integrate RFC 7540 replacement with deprecation notage
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1809 uncontroversial nits from Bob
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1806 Expand on applicability of this scheme for clarity
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1810 trim text to focus on why e2e header
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1812 slight tweak to introduction of reprioritization
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1818 Be less assertive about retransmission
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1817 Problems with HTTP/2 are not our security consideration
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1815 Reword sentence that cites CACHING
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1816 Be specific about the incremental streams guidance we refer to
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1822 Remove redundant text (amends #1803)
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1825 describe fairness and how that relates to priorities
  draft-ietf-httpbis-priority.md
Labels: priorities

#1826 be clear what "precedence" means
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1827 get rid of some "precedence"
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1803 Better articulate server competition challenges
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1814 stop short of saying one-by-one, entirety
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1828 Commas and all that
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1829 "and and" and other minor nits
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1823 Recommend 501 for unknown protocols
  draft-ietf-httpbis-h3-websockets.md
Labels: h3-websockets

#1847 FAQ tidyup
  draft-ietf-httpbis-digest-headers.md
Labels: editorial, digest-headers

#1849 Fix: #1839. Remove cleartext references.
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1852 Fix: #1840. Add syntactic compatibility.
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1855 Corruption of data is not always only accidental
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1856 Simplify IANA algorithm descriptions
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1854 Fix: #1844. Consistent use of checksum.
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1851 Fix: #1841. Reference Algorithm substitution.
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1857 Merge representation digest definition with Digest header one
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1850 Fix: #1842. Remove normative text in sec & IANA.
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1848 Fix: #1834. Remove incremental algorithms.
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1862 Signature Cleanup
  draft-ietf-httpbis-message-signatures.md
Labels: signatures

#1861 Editorial suggestions from Benjamin Kaduk's IESG review (priority)
  draft-ietf-httpbis-priority.md
Labels: priorities

#1866 Make it clearer why and how clients send PRIORITY_UPDATE
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1860 H2 PRIORITY_UPDATE type field is 8 bits
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1870 Lars' nits
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1865 Mark normative statements
  draft-ietf-httpbis-binary-message.md
  draft-ietf-httpbis-client-cert-field.md
  draft-ietf-httpbis-digest-headers.md
  draft-ietf-httpbis-message-signatures.md
Labels: digest-headers, signatures, client-cert-field, binary-messages
