Repository httpwg/http-extensions, pull requests merged in 2021-07, with the labels that each got.

#1559 priorities apply to HTTP and may be used by extensions
  draft-ietf-httpbis-priority.md
Labels: priorities

#1544 priorities: CONNECT can be prioritized too
  draft-ietf-httpbis-priority.md
Labels: priorities

#1567 Fix: #1377. Reboot digest-algorithm values registry.
  draft-ietf-httpbis-digest-headers.md
Labels: digest-headers

#1565 added new specialty content fields, fix request-target
  draft-ietf-httpbis-message-signatures.md
Labels: signatures

#1566 Add request/response binding
  draft-ietf-httpbis-message-signatures.md
Labels: signatures

#1584 s/MAY/can
  draft-ietf-httpbis-priority.md
Labels: priorities

#1575 fix wrong sf- import
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities

#1574 remove a stale TBD
  draft-ietf-httpbis-priority.md
Labels: editorial, priorities
